In [2]:
import numpy as np

### ndarray 기본 연산자
- add, substract, multiply, divide

In [4]:
x = np.random.randint(10, size=(4,3))
y = np.random.randint(10, size=(4,3))
print(x)
print(y)

[[6 8 9]
 [7 0 6]
 [6 5 2]
 [6 0 8]]
[[7 0 0]
 [5 4 1]
 [4 9 3]
 [7 1 4]]


In [5]:
np.add(x,y)

array([[13,  8,  9],
       [12,  4,  7],
       [10, 14,  5],
       [13,  1, 12]])

In [6]:
np.divide(x,y)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.85714286,        inf,        inf],
       [1.4       , 0.        , 6.        ],
       [1.5       , 0.55555556, 0.66666667],
       [0.85714286, 0.        , 2.        ]])

In [7]:
x + y

array([[13,  8,  9],
       [12,  4,  7],
       [10, 14,  5],
       [13,  1, 12]])

In [8]:
# 행렬 곱셈이 아니다!
np.multiply(x,y)

array([[42,  0,  0],
       [35,  0,  6],
       [24, 45,  6],
       [42,  0, 32]])

In [9]:
# 행렬곱 x
x * y

array([[42,  0,  0],
       [35,  0,  6],
       [24, 45,  6],
       [42,  0, 32]])

### ndarray 통계 함수
- 평균(mean), 분산(var), 중앙(median), 최대(max), 최소(min), 표준분산(std)
- axis에 대한 이해

In [10]:
print(x)

[[6 8 9]
 [7 0 6]
 [6 5 2]
 [6 0 8]]


In [11]:
# 평균
np.mean(x)

5.25

In [12]:
x.mean()

5.25

In [13]:
# 최대값
np.max(x)

9

In [14]:
# 최소값
np.min(x)

0

In [16]:
# 분산
np.var(x)

8.354166666666666

In [17]:
# 중앙값
np.median(x)

6.0

In [21]:
arr = x.flatten()
arr.sort()
print(arr)

[0 0 2 5 6 6 6 6 7 8 8 9]


In [18]:
# 표준분산
np.std(x)

2.890357532670771

### ndarray 집계(aggregation)
- 합(sum), 누적합(cumsum)

In [24]:
print(x)

[[6 8 9]
 [7 0 6]
 [6 5 2]
 [6 0 8]]


In [22]:
np.sum(x)

63

In [33]:
np.sum(x, axis = 0)

array([25, 13, 25])

In [34]:
np. sum(x, axis =1)

array([23, 13, 13, 14])

In [23]:
np.cumsum(x)

array([ 6, 14, 23, 30, 30, 36, 42, 47, 49, 55, 55, 63])

### any, all 함수
- any: 특정 조건을 만족하는 값이 하나라도 있으면 True
- all: 모든 원소가 조건을 만족하면 True

In [25]:
print(x)

[[6 8 9]
 [7 0 6]
 [6 5 2]
 [6 0 8]]


In [26]:
x>5

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False, False],
       [ True, False,  True]])

In [27]:
np.any(x>5)

True

In [28]:
np.all(x>5)

False

In [29]:
np.all(x>=0)

True

### where 함수
- 조건에 따라 참인 값만 선택
- 조건에 맞지 않는 경우 인자의 값을 사용

In [30]:
print(x)

[[6 8 9]
 [7 0 6]
 [6 5 2]
 [6 0 8]]


In [32]:
np.where(x > 5, x, 0)

array([[6, 8, 9],
       [7, 0, 6],
       [6, 0, 0],
       [6, 0, 8]])

#### axis(축): x축, y축
- 함수의 인자로 axis를 인자로 갖는 함수들이 존재
- 2차원 배열에서는 행, 열로 확인
- 아래의 함수들을 이용해 확인

#### 1차원 배열의 경우

In [36]:
arr = np.random.randint(10, size=(5,))
print(arr)

[5 0 9 3 5]


In [37]:
arr.sum()

22

In [39]:
arr.sum(axis=0) # 1차원 배열일 경우 axis를 사용하지 않아도 무관하다.

22

In [40]:
arr.sum(axis=1) # 1차원 배열이므로 축이 밀려서 나는 오류(AxisError)

AxisError: axis 1 is out of bounds for array of dimension 1

#### 2차원 배열의 경우

In [55]:
np.random.seed(101)
arr = np.random.randint(10, size=(2,3))
print(arr)
print(arr.shape)

[[1 6 7]
 [9 8 4]]
(2, 3)


In [56]:
arr.sum()

35

In [57]:
# axis = 0은 행을 뜻한다
# 행을 기준으로 모든 열의 값을 더한다
arr.sum(axis=0)

array([10, 14, 11])

In [58]:
# axis = 1은 열을 뜻한다
# 열을 기준으로 모든 행의 값을 더한다
arr.sum(axis=1)

array([14, 21])

In [50]:
arr.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

#### axis를 이용해서 평균(mean()) 구하기

In [59]:
arr.mean()

5.833333333333333

In [60]:
arr.mean(axis=0)

array([5. , 7. , 5.5])

In [61]:
arr.mean(axis=1)

array([4.66666667, 7.        ])