In [4]:
import numpy as np

## ndarray 데이터 생성하기(랜덤)
- zeros, ones, linspace, ...외에 추가로
- random 모듈의 함수를 통해 ndarray 생성

### rand: 0,1 사이에 랜덤한 ndarray를 생성

In [6]:
np.random.rand(10)

array([0.73449325, 0.69760352, 0.36355903, 0.95632392, 0.02007786,
       0.82751016, 0.82679997, 0.53317871, 0.61505685, 0.58370039])

In [7]:
# 다차원 ndarray도 생성 가능하다.
np.random.rand(4,3)

array([[0.60008292, 0.80229753, 0.80693585],
       [0.28592136, 0.19250123, 0.59554021],
       [0.14932162, 0.13857706, 0.04331257],
       [0.90598631, 0.88812844, 0.5569352 ]])

### randn(random normal distribution)
- 정규분포
- 정규분포로 샘플링된 랜덤한 데이터를 생성

In [8]:
np.random.randn(5)

array([-1.30819412,  1.05744564, -0.1564814 ,  1.44211882, -1.13481172])

In [9]:
np.random.randn(4,3)

array([[-1.0234792 , -0.12736771, -0.79678668],
       [ 1.03536892,  0.56047554, -0.55500528],
       [ 0.60479155,  0.29679129, -0.0214006 ],
       [ 0.71446262,  0.40795256,  0.25960531]])

### randint
- 지정된 정수 사이에서 랜덤한 ndarray를 생성

In [10]:
np.random.randint(1, 10)

7

In [11]:
np.random.randint(1, 10, size=(5))

array([3, 5, 4, 8, 4])

In [12]:
np.random.randint(1, 10, size=(4,3))

array([[3, 3, 3],
       [6, 5, 8],
       [5, 7, 6],
       [5, 5, 7]])

### choice
- 주어진 정수나, 1차원 ndarray로 부터 랜덤하게 샘플링하여 ndarray를 생성

In [13]:
# np.arange(10)한 ndarray로 부터 랜덤하게 샘플링(초이스)
np.random.choice(10, size=(4,3))

array([[9, 0, 8],
       [9, 2, 8],
       [5, 2, 1],
       [4, 9, 0]])

In [15]:
x = np.arange(10)
np.random.choice(x, size=(4,3))

array([[4, 0, 8],
       [1, 1, 1],
       [4, 3, 7],
       [0, 5, 0]])

### 확률분포에 따른 ndarray 생성
- 잘 알려진 분포: 정규, 포아송, 베타분포, ...
- 수집된 데이터로부터 확률 분포를 구할 수 있다.

In [16]:
np.random.uniform(1.0, 3.0, size=(4,3))

array([[1.8047528 , 2.10397225, 1.69904856],
       [1.78668297, 1.86102234, 2.00885547],
       [2.41345786, 1.25867147, 2.52368613],
       [2.82249405, 2.75172805, 2.26235039]])

In [17]:
np.random.normal(size=(4,3))

array([[ 1.08246563, -0.11154358, -0.55511999],
       [-0.16070325,  1.12928504,  0.80882094],
       [ 0.72167758,  1.75028219,  0.22607822],
       [ 1.10378114,  0.7384983 ,  0.75618076]])

In [18]:
np.random.randn(4,3)

array([[ 0.06056824, -0.3310758 , -0.25599477],
       [ 1.32717392,  0.19783536, -1.34976716],
       [ 1.09733598,  0.99237247, -0.50281735],
       [ 0.48913868,  0.62957294,  0.53638938]])

### seed
- 랜덤 데이터 생성의 기준
- 랜덤하게 생성된 값을 고정시키고 싶은 경우

In [26]:
np.random.seed(10)
np.random.randn(10,3)

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737],
       [-0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489, -1.97772828],
       [-1.7433723 ,  0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221,  0.09914922],
       [ 1.39799638, -0.27124799,  0.61320418]])

## 다차원을 1차원으로 변경

In [28]:
arr = np.random.randint(100, size=(4,3))
print(arr)

[[15 18 80]
 [71 88 11]
 [17 46  7]
 [75 28 33]]


In [33]:
# default: row 우선 변경
np.ravel(arr, order='C')

array([15, 18, 80, 71, 88, 11, 17, 46,  7, 75, 28, 33])

In [35]:
# 'F': column 우선 변경
np.ravel(arr, order='F')

array([15, 71, 17, 75, 18, 88, 46, 28, 80, 11,  7, 33])

In [37]:
arr.ravel()

array([15, 18, 80, 71, 88, 11, 17, 46,  7, 75, 28, 33])

In [38]:
arr.ravel(order='F')

array([15, 71, 17, 75, 18, 88, 46, 28, 80, 11,  7, 33])

In [32]:
arr.flatten()

array([15, 18, 80, 71, 88, 11, 17, 46,  7, 75, 28, 33])

In [39]:
arr.flatten(order='F')

array([15, 71, 17, 75, 18, 88, 46, 28, 80, 11,  7, 33])