In [2]:
import numpy as np

# numpy의 행렬

- np.matrix: 수학적 연산
- np.array: 머신러닝에 많이 사용한다.

### matrix 생성

In [2]:
A = np.matrix('1,2,3,4; 5,6,7,8; 9,10,11,12')
x = np.matrix('1;2;3;4')
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### array 생성

In [4]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

x = np.array([
    [1],
    [2],
    [3],
    [4]
])

print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### 행렬 곱셈
- 행렬의 덧셈은 별거 없다

### 행렬/ 벡터곱
- 첫번째와 두번째가 있습니다 (노트에)

In [13]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1))
n = 4

# todo matrix를 이용한 행렬곱 결과를 출력
#b = A * x
for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i, j] * x[j,0]
    b[i] = val
    
print(b)

[[15.]
 [19.]
 [26.]
 [44.]]


In [15]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4

for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i, j] * x[j]
    b[i] = val

print(b)

[15 19 26 44]


In [16]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print(x)

b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]
[15 19 26 44]
[15 19 26 44]


## 행렬과 Array 곱셈

In [21]:
A = np.matrix('4,5,2,1; 2,3,8,0; 1,0,7,2')
x = np.matrix('1;2;3;4')

In [36]:
# for loop를 이용한 행렬/벡터 곱 구현
b = np.zeros((3,1))
for i in range(3):
    val = 0.0
    for j in range(4):
        val += A[i, j] * x[j,0]
    b[i] = val

print(b)

[[24.]
 [32.]
 [30.]]


In [37]:
# matrix 타입의 행렬/벡터 곱 구현
c = A * x
print(c)

[[24]
 [32]
 [30]]


In [41]:
A = np.array([[4,5,2,1], [2,3,8,0], [1,0,7,2]])
x = np.array([1,2,3,4])

In [38]:
# for loop이용: array 행렬/벡터 곱 구현

b = np.zeros(3)

for i in range(3):
    val = 0.0
    for j in range(4):
        val += A[i, j] * x[j]
    b[i] = val

print(b)

[24. 32. 30.]


In [42]:
# array를 곱하는 방법:하나 더

b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[24 32 30]
[24 32 30]
